import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang="en">
            <body className="m-auto grid grid-rows-[auto_1fr_auto] min-h-screen gap-8 p-8 w-[min(95vw,1000px)]">
                <header className="min-h-[3rem] flex justify-between gap-[10px] items-center w-full">
                    <div className="flex flex-row gap-6">
                        <span>logo</span>
                        <nav>nav</nav>
                    </div>
                    <div>yeet</div>
                </header>
                <main className="flex-grow h-[200vh] bg-pink-50">
                    {children}
                </main>
                <footer>footer</footer>
            </body>
        </html>
    );
}
