import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Header from "./components/header";
import Footer from "./components/footer";
import QueryProvider from "./components/query";
const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang="en">
            <body className="m-auto grid grid-rows-[auto_1fr_auto] min-h-screen gap-8 p-8 w-[min(95vw,2000px)]">
                <QueryProvider>
                    <Header />
                    <main>{children}</main>
                    <Footer />
                </QueryProvider>
            </body>
        </html>
    );
}
